/**
 * LUT 的展示名。
 *
 * 名字不只是给眼睛看的：`addCustomLuts` 拿它当库里的去重键（同名视为替换），
 * 所以两件不同的事共用一个字符串——想显示的，与想复用同一条目的。
 *
 * `.cube` 的 `TITLE` 理论上正是干这个用的，但有的导出器把它写成一句套话：
 * Resolve 从「剪辑」页导出的每一个 LUT，`TITLE` 都是同一句 `Generated by Resolve`。
 * 直接采用，一批文件的展示名就全一样，于是互相顶掉，下拉框里只剩最后导入的那一个。
 * 这类套话当作「没有名字」，退回文件名——文件名是用户自己挑的，通常带得上
 * 「Kodak 2383 D60」这样的区分信息。
 */

/**
 * 当作没写名字的 `TITLE`。
 *
 * 不区分大小写地找子串：导出器会在这句话后面接版本号（`Generated by Resolve - v1.0`）
 * 之类的尾巴，整句相等会漏掉这些。这些是套话而不是片名，放宽匹配不会误伤
 * 一个真叫这个名字的 LUT。
 */
const MEANINGLESS_TITLES: readonly string[] = ['generated by resolve'];

/** `TITLE` 是否是导出器的套话 */
export function isMeaninglessLutTitle(title: string | undefined | null): boolean {
  if (!title) return true;
  const normalized = title.trim().toLowerCase();
  return MEANINGLESS_TITLES.some((meaningless) => normalized.includes(meaningless));
}

/** 挑一个当展示名的字符串：LUT 自带的 `TITLE` 优先，套话或没写时用文件名 */
export function resolveLutDisplayName(title: string | undefined | null, fileName: string): string {
  const trimmed = title?.trim() ?? '';
  return isMeaninglessLutTitle(trimmed) ? fileName : trimmed;
}
