import { create } from 'zustand';
import { findLogSpace, logSpaceIndex, type LogSpaceId } from '../color/log-spaces';
import { loadOfficialLut, officialLutEntries } from '../lut/official-luts';
import type { Lut3D } from '../lut/types';
import type { FileEntry, FolderBrowseResult } from '../types/image';
import { DEFAULT_ADJUSTMENTS, clampAdjustment, type ImageAdjustments } from '../types/adjustments';

export type AppStatus = 'empty' | 'loading' | 'ready' | 'error';

/** 用户从文件载入的 LUT */
export interface LoadedLut {
  /** 库里的唯一键：同名再导入视为替换，键保持不变 */
  key: string;
  /**
   * 展示名，同时也是库里的去重键：优先用 LUT 自带的 TITLE，没有就用文件名。
   *
   * 由 `resolveLutDisplayName` 判定，导出器写的套话（Resolve 的
   * `Generated by Resolve`）不算名字——见那个模块的注释。
   */
  name: string;
  lut: Lut3D;
}

export interface AppState {
  /** 当前文件夹名 */
  folderName: string | null;
  /** 当前文件夹内的图片 */
  images: FileEntry[];
  /** 当前查看的图片下标，-1 表示没有选中 */
  currentIndex: number;
  status: AppStatus;
  error: string | null;

  /** 调整参数，作用于当前图片 */
  adjustments: ImageAdjustments;
  /** 当前选中的官方 LUT 键（`officialLutEntries` 里的 key），null 为不使用 */
  officialLutKey: string | null;
  /** 选中的官方 LUT 的解析结果；未选中或还在载入时为 null */
  officialLut: Lut3D | null;
  /** 官方 LUT 正在载入 */
  officialLutLoading: boolean;
  /**
   * 官方 LUT 载入失败的原因。
   *
   * 只就地展示在 LUT 面板里，**不写进 `error`**：那会把 status 打成 error 并盖掉整个界面，
   * 而一个读不出来的 LUT 不该让用户看不到正在看的图（与 #25 对坏文件的处理一致）。
   */
  officialLutError: string | null;
  /**
   * 已从文件载入的 LUT 库，按导入顺序。
   *
   * 库与「当前选中」是两件事：可以导入一堆 LUT 而一个都不选中。
   * 同名（按展示名，即 `LoadedLut.name`）再导入视为替换那个条目，列表与选择都不会跳。
   */
  lutLibrary: LoadedLut[];
  /** 库中当前生效的 LUT 键；null 表示不用自定义 LUT（回落到官方 LUT 或原图） */
  customLutKey: string | null;
  /** 当前选中的 Log 色彩空间，null 表示关闭（按 sRGB 显示） */
  logSpaceId: LogSpaceId | null;
  /**
   * LUT 的输出是否仍在 Log 空间。
   *
   * 默认 false：LUT 输出已是显示空间，直接显示——ARRI 的 `LogC4 → Rec.709` 这类
   * 技术转换就是这样，把它当 Log 再解码一次会得到纯青的天空。
   * 置 true 用于串联「Log 进、Log 出」的 LUT。
   */
  lutOutputEncoded: boolean;

  // ---- actions ----
  setFolder: (result: FolderBrowseResult) => void;
  clearFolder: () => void;
  selectImage: (index: number) => void;
  nextImage: () => void;
  previousImage: () => void;
  setAdjustment: <K extends keyof ImageAdjustments>(key: K, value: number) => void;
  resetAdjustments: () => void;
  /** 选中一个官方 LUT；传 null 或清单里没有的键都回到「不使用」 */
  setOfficialLut: (key: string | null) => void;
  /** 清掉当前生效的 LUT：官方的那份与导入的那份一起 */
  clearActiveLut: () => void;
  /**
   * 把一批解析好的 LUT 加进库（同名替换），并在当前没有选中项时自动选第一个。
   */
  addCustomLuts: (entries: Array<Omit<LoadedLut, 'key'>>) => void;
  /** 选中库里的某个 LUT；传 null 表示不用自定义 LUT */
  setActiveCustomLut: (key: string | null) => void;
  /** 从库里移除一个 LUT；移除的是当前选中项时自动回退 */
  removeCustomLut: (key: string) => void;
  /** 传 null 或未知 id 都表示关闭 Log 模式 */
  setLogSpace: (id: string | null) => void;
  /** LUT 的输出是否仍在 Log 空间；见 AppState.lutOutputEncoded */
  setLutOutputEncoded: (encoded: boolean) => void;
  setStatus: (status: AppStatus) => void;
  setError: (message: string | null) => void;
}

/** 选中下标是否有效 */
function isValidIndex(index: number): boolean {
  return Number.isInteger(index) && index >= 0;
}

/** 已导入 LUT 的键计数器；模块级，与 store 生命周期一致 */
let nextLutKey = 1;

/** 官方 LUT 载入的竞态令牌：快速连点下拉框时，只让最后一次的结果落地 */
let officialLutLoadToken = 0;

/**
 * 清掉官方 LUT：选择、解析结果、载入状态、错误一起。
 *
 * 这四样是一组——`officialLut` 只对应 `officialLutKey`，只清选择会留下
 * 「选着 A 却挂着 B 的数据」这种状态。解析结果在 `official-luts` 里另有缓存，
 * 再选回来不会重新解析。
 */
function clearedOfficialLut() {
  officialLutLoadToken += 1;
  return {
    officialLutKey: null,
    officialLut: null,
    officialLutLoading: false,
    officialLutError: null,
  };
}

/**
 * 编辑态复位：换文件夹时把调整参数、LUT 选择与 Log 选择清掉。
 *
 * `lutLibrary` **不清**：导入的 LUT 是用户花了功夫准备的素材，换文件夹不该丢；
 * 换文件夹时只是不再选中它（回落到原图）。
 */
function clearedEditState() {
  return {
    adjustments: { ...DEFAULT_ADJUSTMENTS },
    ...clearedOfficialLut(),
    customLutKey: null,
    logSpaceId: null,
    lutOutputEncoded: false,
  };
}

export const useAppStore = create<AppState>((set, get) => ({
  folderName: null,
  images: [],
  currentIndex: -1,
  status: 'empty',
  error: null,
  adjustments: { ...DEFAULT_ADJUSTMENTS },
  ...clearedOfficialLut(),
  lutLibrary: [],
  customLutKey: null,
  logSpaceId: null,
  lutOutputEncoded: false,

  setFolder: (result) => {
    const hasImages = result.images.length > 0;
    set({
      folderName: result.folderName,
      images: result.images,
      currentIndex: hasImages ? 0 : -1,
      status: hasImages ? 'ready' : 'empty',
      error: hasImages ? null : '该文件夹里没有支持的图片',
      ...clearedEditState(),
    });
  },

  clearFolder: () =>
    set({
      folderName: null,
      images: [],
      currentIndex: -1,
      status: 'empty',
      error: null,
      ...clearedEditState(),
    }),

  selectImage: (index) => {
    const { images } = get();
    if (!isValidIndex(index) || index >= images.length) return;
    set({ currentIndex: index });
  },

  nextImage: () => {
    const { images, currentIndex } = get();
    if (currentIndex < images.length - 1) {
      set({ currentIndex: currentIndex + 1 });
    }
  },

  previousImage: () => {
    const { currentIndex } = get();
    if (currentIndex > 0) {
      set({ currentIndex: currentIndex - 1 });
    }
  },

  setAdjustment: (key, value) =>
    set((state) => ({
      adjustments: { ...state.adjustments, [key]: clampAdjustment(key, value) },
    })),

  resetAdjustments: () => set({ adjustments: { ...DEFAULT_ADJUSTMENTS } }),

  setOfficialLut: (key) => {
    // 只认清单里有的键：UI 传回来的字符串不可信。null 与「不认识」都落到「不使用」。
    const entry =
      key === null
        ? null
        : (officialLutEntries(get().logSpaceId).find((item) => item.key === key) ?? null);
    const token = ++officialLutLoadToken;

    if (!entry) {
      set(clearedOfficialLut());
      return;
    }

    set({
      officialLutKey: entry.key,
      officialLut: null,
      officialLutLoading: true,
      officialLutError: null,
      // 官方 LUT 与导入的 LUT 互斥：同一个画面上只该有一个 LUT 生效
      customLutKey: null,
    });

    // 只有「还是同一次载入」才允许落地：中途换了选择或换了色彩空间，这次结果就作废
    const isCurrent = () => token === officialLutLoadToken && get().officialLutKey === entry.key;

    loadOfficialLut(entry)
      .then((lut) => {
        if (!isCurrent()) return;
        set({ officialLut: lut, officialLutLoading: false, officialLutError: null });
      })
      .catch((error: unknown) => {
        if (!isCurrent()) return;
        set({
          officialLut: null,
          officialLutLoading: false,
          officialLutError: (error as Error).message,
        });
      });
  },

  clearActiveLut: () => set({ ...clearedOfficialLut(), customLutKey: null }),

  addCustomLuts: (entries) =>
    set((state) => {
      const library = [...state.lutLibrary];
      for (const entry of entries) {
        const existing = library.findIndex((item) => item.name === entry.name);
        // 同名视为替换：键保持不变，选择与顺序都不会跳
        const key = existing >= 0 ? library[existing].key : `lut-${nextLutKey++}`;
        const loaded: LoadedLut = { ...entry, key };
        if (existing >= 0) library[existing] = loaded;
        else library.push(loaded);
      }

      // 目前没选中任何自定义 LUT 时，导入后自动选第一个，省掉一次手动点击；
      // 这一步会让官方 LUT 让位，但只在选择真的动了的时候——同名替换不该动当前画面
      const selectedExists =
        state.customLutKey !== null && library.some((item) => item.key === state.customLutKey);
      const customLutKey = selectedExists ? state.customLutKey : (library[0]?.key ?? null);

      return {
        lutLibrary: library,
        customLutKey,
        ...(customLutKey === state.customLutKey ? {} : clearedOfficialLut()),
      };
    }),

  setActiveCustomLut: (key) =>
    set((state) => {
      if (key === null) return { customLutKey: null };
      // 只认库里有的键：UI 传回来的字符串不可信
      if (!state.lutLibrary.some((item) => item.key === key)) return {};
      // 选了导入的 LUT，官方那份就让位：同一个画面上只该有一个生效
      return { customLutKey: key, ...clearedOfficialLut() };
    }),

  removeCustomLut: (key) =>
    set((state) => {
      const library = state.lutLibrary.filter((item) => item.key !== key);
      if (library.length === state.lutLibrary.length) return {};

      // 删掉的是当前选中项就回退到剩下的第一个；不是的话保持选择
      let customLutKey = state.customLutKey;
      if (customLutKey !== null && !library.some((item) => item.key === customLutKey)) {
        customLutKey = library[0]?.key ?? null;
      }
      return { lutLibrary: library, customLutKey };
    }),

  // 只认表里有的 id：UI 传回来的字符串不可信，脏值会让着色器下标越界。
  // 关掉（null）与「不认识」都落到 null，所以分开判断，不拿空串当哨兵。
  // 换色彩空间就是换一份 LUT 清单：上一个空间选的官方 LUT 在新空间里没有意义，跟着清掉。
  setLogSpace: (id) => {
    const logSpaceId = (id === null ? undefined : findLogSpace(id))?.id ?? null;
    set({ logSpaceId, ...clearedOfficialLut() });
  },

  setLutOutputEncoded: (encoded) => set({ lutOutputEncoded: encoded }),

  setStatus: (status) => set({ status }),

  setError: (message) => set({ error: message, status: message ? 'error' : get().status }),
}));

/** 当前图片；没有选中时为 null */
export function selectCurrentImage(state: AppState): FileEntry | null {
  const { images, currentIndex } = state;
  if (!isValidIndex(currentIndex) || currentIndex >= images.length) return null;
  return images[currentIndex];
}

/**
 * 当前生效的 LUT：选中的自定义 LUT 优先，其次官方 LUT，都没有则为 null。
 *
 * 两者互斥（选一个会清掉另一个），这里的先后只是兜底；选择项指向一个已不存在的
 * 键（库被清过）时按「没选」处理。
 */
export function selectActiveLut(state: AppState): Lut3D | null {
  const custom = state.lutLibrary.find((item) => item.key === state.customLutKey)?.lut ?? null;
  return custom ?? state.officialLut;
}

/**
 * 选中的自定义 LUT；没有选中或键已失效时为 null。
 * UI 需要拿到名字与库条目时用它，别自己 find。
 */
export function selectCustomLut(state: AppState): LoadedLut | null {
  return state.lutLibrary.find((item) => item.key === state.customLutKey) ?? null;
}

/**
 * 当前 Log 空间的下标，关闭时为 -1。
 * 这个数字同时是着色器 uniform 的取值，UI 与渲染器都从这里取，避免两处各算一遍。
 */
export function selectLogSpaceIndex(state: AppState): number {
  return logSpaceIndex(state.logSpaceId);
}

/** 是否挂了 LUT（官方 LUT 或载入的文件），用来提示 LUT 会在 Log 空间里作用 */
export function selectHasLut(state: AppState): boolean {
  return selectActiveLut(state) !== null;
}
