import { act, renderHook } from '@testing-library/react';
import { beforeEach, describe, expect, it } from 'vitest';
import { useAppStore } from '../store/useAppStore';
import { useLutImport } from './useLutImport';

/**
 * 2×2×2 的恒等 .cube。
 *
 * `title` 用替换的方式塞进去，而不是拼一个占位符——测试要读的是真实的
 * `TITLE "..."` 那一行，拼出来的字符串得能被 `parse-cube` 原样认出来。
 */
function cubeFile(title?: string): string {
  const header = title === undefined ? '' : `TITLE "${title}"\n`;
  return `${header}LUT_3D_SIZE 2
0 0 0
1 0 0
0 1 0
1 1 0
0 0 1
1 0 1
0 1 1
1 1 1
`;
}

const initialState = useAppStore.getState();

/** 走一遍真实的导入路径：文件 → 解析 → 入列 */
async function importFiles(files: File[]): Promise<void> {
  const { result } = renderHook(() => useLutImport());
  await act(async () => {
    await result.current.importLutFiles(files);
  });
}

describe('useLutImport', () => {
  beforeEach(() => {
    useAppStore.setState(initialState, true);
  });

  it('用 LUT 自带的 TITLE 当展示名', async () => {
    await importFiles([new File([cubeFile('Imported Look')], 'look.cube')]);

    expect(useAppStore.getState().lutLibrary.map((entry) => entry.name)).toEqual(['Imported Look']);
  });

  it('没有 TITLE 时退回文件名', async () => {
    await importFiles([new File([cubeFile()], 'no-title.cube')]);

    expect(useAppStore.getState().lutLibrary.map((entry) => entry.name)).toEqual(['no-title.cube']);
  });

  /**
   * Resolve 从「剪辑」页导出的每一个 .cube，TITLE 都是同一句 "Generated by Resolve"。
   *
   * 展示名同时是库里的去重键（同名视为替换），拿这句话当名字，一批文件会互相顶掉，
   * 下拉框里只剩最后导入的那一个。
   */
  it('Resolve 导出的文件用文件名区分，不会互相顶掉', async () => {
    await importFiles([
      new File([cubeFile('Generated by Resolve')], 'Kodak 2383 D60.cube'),
      new File([cubeFile('Generated by Resolve')], 'Fuji 3510 D60.cube'),
      new File([cubeFile('Generated by Resolve')], 'Kodak 2393 D65.cube'),
    ]);

    expect(useAppStore.getState().lutLibrary.map((entry) => entry.name)).toEqual([
      'Kodak 2383 D60.cube',
      'Fuji 3510 D60.cube',
      'Kodak 2393 D65.cube',
    ]);
  });

  it('同一句话大小写或带版本后缀时，也当作没有名字', async () => {
    await importFiles([
      new File([cubeFile('generated by resolve')], 'lower.cube'),
      new File([cubeFile('Generated by Resolve - v1.0')], 'suffixed.cube'),
    ]);

    expect(useAppStore.getState().lutLibrary.map((entry) => entry.name)).toEqual([
      'lower.cube',
      'suffixed.cube',
    ]);
  });

  it('有真正名字的仍旧用名字，即使文件名不同', async () => {
    await importFiles([
      new File([cubeFile('Kodak 2383')], 'a.cube'),
      new File([cubeFile('Fuji 3510')], 'b.cube'),
    ]);

    expect(useAppStore.getState().lutLibrary.map((entry) => entry.name)).toEqual([
      'Kodak 2383',
      'Fuji 3510',
    ]);
  });
});
